/home/servicing/projects/environments/anaconda3/envs/py37_torch_jiarui/bin/python -u main.py \
--model "prnet" \
--loss_fn "reg" \
--batch_size 16 \
--cuda '0' \
--epochs 100 \
--step_size 10 \
--lr 1.e-3 \
--optim "Adam" \
--version "prnet" \
--trainer 'prnet' \
--lr_scheduler 'warmup' \
--gamma 0.8